spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop
