CREATE TABLE client
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cpf     VARCHAR(11),
    name    VARCHAR(255),
    number  BIGINT,
    balance DECIMAL,
    CONSTRAINT pk_client PRIMARY KEY (id)
);

CREATE TABLE transaction
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_time   TIMESTAMP WITHOUT TIME ZONE,
    description VARCHAR(255),
    value       DECIMAL,
    client_id   BIGINT,
    type        VARCHAR(255),
    CONSTRAINT pk_transaction PRIMARY KEY (id)
);

ALTER TABLE client
    ADD CONSTRAINT uc_client_cpf UNIQUE (cpf);

ALTER TABLE transaction
    ADD CONSTRAINT FK_TRANSACTION_ON_CLIENT FOREIGN KEY (client_id) REFERENCES client (id);