name: Bankline Build

on:
  pull_request:
    branches: [ master ]

jobs:
  validation:
    name: Gradle Wrapper Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1

  build:
    name: Build
    needs: validation
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: bankline
          gradle-executable: bankline/gradlew
